project:
  type: website
  preview:
    watch-inputs: true

website:
  title: "MND ⚙️"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Courses"
        menu:
          - PY211IB/index.qmd
          - CI114TA/index.qmd
          - MA211TB/index.qmd
    tools:
      - icon: github
        href: https://github.com/brinterwastaken/mech-notes-directory

  sidebar:
    contents: auto

format:
  html:
    theme:
      - litera
    css: styles.css
    toc: true
    number-sections: true