---
title: "Elementary Linear Algebra"
subtitle: "<a href='javascript:void(0)' onclick='window.print()' class='btn btn-outline-primary btn-sm' role='button'>Download/Print</a>"
format: html
---

- Elementary linear algebra is the study of lines, planes, and multidimensional spaces using vectors and matrices.

- To understand the concepts of this unit, it is important to have a basic understanding of matrices (types of matrices, matrix operations, etc.) and determinants.

# Submatrices and Minors

## Submatrix

- A matrix obtained from a given matrix by deleting some rows and/or columns.

### Example

::: {.grid}

::: {.g-col-12 .g-col-md-6}
For the below matrix,
$$
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16 \\
\end{bmatrix}
$$
:::

::: {.g-col-12 .g-col-md-6}
The submatrix obtained by deleting the first row and the second column is

$$
\begin{bmatrix}
5 & 7 & 8 \\
9 & 11 & 12 \\
13 & 15 & 16 \\
\end{bmatrix}
$$
:::

:::

## Minor of a matrix

- The minor of a matrix is the determinant of the submatrix obtained by deleting some rows and/or columns.

### Example

::: {.grid}
::: {.g-col-12 .g-col-md-6}
For the below matrix, 
$$
\begin{bmatrix}
1 & 4 & 6 & 3 \\
2 & 3 & 4 & 4 \\
6 & 2 & 1 & 2 \\
\end{bmatrix}
$$
:::

::: {.g-col-12 .g-col-md-6}
We can evaluate the minor as follows:
$$
\begin{vmatrix}
1 & 4 & 6 \\
2 & 3 & 4 \\
6 & 2 & 1 \\
\end{vmatrix} = -1
$$
:::

:::

- The above example illustrates a minor of order 3 for the given matrix. Similarly, minors of lower orders can also be evaluated.

# Rank of a Matrix

- The rank of a matrix $A_{m \times n}$, is $r$ if there exists atleast one non-zero minor of order $r$, and all minors above the order $r$ are zero/non existent.

- i.e., the rank of a matrix is the order of its largest non-zero minor.

- It is denoted as $\rho(A)$.

## Examples

1. For the below matrix, we can take a non zero 3rd order minor as follows:

$$
A = 
\begin{bmatrix}
1 & 3 & 2 & 1 \\
4 & 2 & 1 & 4 \\
2 & 1 & 2 & 2 \\
\end{bmatrix}
\hspace{1cm}
\begin{vmatrix}
1 & 3 & 2 \\
4 & 2 & 1 \\
2 & 1 & 2 \\
\end{vmatrix} = -15 \implies \boxed{\rho(A) = 3}
$$

2. For the below matrix, all minors of order 4,3,2 are zero, and it is not a null matrix, thus $\rho(B) = 1$

$$
\begin{bmatrix}
1 & 4 & 3 & 2 \\
1 & 4 & 3 & 2 \\
1 & 4 & 3 & 2 \\
1 & 4 & 3 & 2 \\
\end{bmatrix}
$$

## Some Useful Properties

1. $\rho(A) = \rho(A^T)$

2. $\text{if } |A_{n}| \ne 0, \rho(A) = n$ 

3. $\text{if } |A_{n}| = 0, \rho(A) < n$

4. $\rho(I_n) = n$

5. $\rho(A_{m\times n}) \le min(m,n)$

# Elementary Transformations

**Representation:**

1. Interchange of any two rows: $R_i \leftrightarrow R_j$
2. Multiplication of elements of any row by a non-zero number: $R_i \rightarrow kR_i$
3. Addition of corresponding elements of any row to that of another row:
   i.e., addition of $k$ times $j$-th row to $i$-th row is denoted as: $R_i \rightarrow R_i + kR_j$

::: {.callout-note}
Elementary transformations do not change the rank of a matrix.
:::

# Echelon Form of a Matrix

A matrix $A_{m \times n}$ is said to be in Echelon form if:

i) Any zero row (if it exists) is below the non-zero rows.
ii) The number of zeros before the first non-zero element in a non-zero row increases with the row number.

If $A$ is in Echelon form, the rank of $A$ is equal to the number of non-zero rows of $A$.

## Examples

$A = \begin{bmatrix} 1 & 0 & 4 & 3 & 2 & 1 \\ 0 & 2 & 4 & 8 & 4 & 6 \\ 0 & 0 & 0 & 9 & 3 & 2 \\ 0 & 0 & 0 & 0 & 0 & 5 \\ 0 & 0 & 0 & 0 & 0 & 0 \end{bmatrix}$

- Here, $A$ is in Echelon form.

  Number of non-zero rows = $4$
$\implies \rho(A) = 4$

---

$B = \begin{bmatrix} 2 & 3 & 4 & 0 \\ 0 & 0 & 2 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$

- Here, there are no zero rows, and the rows are arranged in the correct order.

  $B$ is in Echelon form with $\rho(B) = 3$

---

$C = \begin{bmatrix} 3 & 0 & 0 & 4 & 5 \\ 0 & 1 & 2 & 3 & 4 \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 2 & 4 & 6 & 8 \end{bmatrix}$

- Here, $C$ is not in Echelon form.

  If we apply $R_4 \rightarrow R_4 - 2R_2$, we get:

  $\begin{bmatrix} 3 & 0 & 0 & 4 & 5 \\ 0 & 1 & 2 & 3 & 4 \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \end{bmatrix} \implies \rho(C) = 2$

- Similarly, $\begin{bmatrix} 1 & 2 & 4 \\ 2 & 4 & 6 \\ 0 & 0 & 0 \end{bmatrix}$ can be reduced to $\begin{bmatrix} 1 & 2 & 4 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}$ (using $R_2 \rightarrow R_2 - 2R_1$)
Thus, the rank is $1$.

## Finding the rank of a matrix by conversion to Echelon form

::: {.callout-tip}
### Steps to convert to Echelon form
a) Check/convert the first element of the first row to $1$.
b) Convert all elements below the first element to zero.
c) Next, use the second row's second element to convert all elements below it to zero.
e) Interchange rows when required.
d) Repeat until Echelon form is achieved.
:::

### Example

$$
A = \begin{bmatrix} 
1 & 2 & 3 & 2 \\ 
2 & 3 & 5 & 1 \\ 
1 & 3 & 4 & 5 
\end{bmatrix}
$$
$$
R_2 \rightarrow R_2 - 2R_1, \quad R_3 \rightarrow R_3 - R_1 \\
\Downarrow \\
\begin{bmatrix} 
1 & 2 & 3 & 2 \\
0 & -1 & -1 & -3 \\ 
0 & 1 & 1 & 3 
\end{bmatrix}
$$

$$
R_3 \rightarrow R_3 + R_2 \\
\Downarrow \\
\begin{bmatrix} 
1 & 2 & 3 & 2 \\
0 & -1 & -1 & -3 \\ 
0 & 0 & 0 & 0 
\end{bmatrix}
$$

This matrix is in Echelon form.

Number of non-zero rows $= 2$

$$
\implies \boxed{\rho(A) = 2}
$$